<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.hawt.examples</groupId>
  <artifactId>hawtio-examples</artifactId>
  <packaging>pom</packaging>
  <version>4.4.0-SNAPSHOT</version>
  <name>Hawtio Examples</name>
  <description>Hawtio :: Examples</description>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

    <hawtio-version>4.4.0.redhat-00024</hawtio-version>

    <!-- Versions for major components -->
    <!-- Jolokia -->
    <jolokia-integration-version>0.9.0</jolokia-integration-version>
    <!-- Quarkus -->
    <quarkus-version>3.33.1.redhat-00006</quarkus-version>
    <!-- Spring Boot 3 -->
    <spring-boot-version>3.5.14</spring-boot-version>
    <!-- Camel -->
    <!-- https://access.redhat.com/articles/7021827#headerCSB -->
    <camel-spring-boot-version>4.18.1.redhat-00014</camel-spring-boot-version>
    <!-- Jetty -->
    <jetty12-version>12.1.8</jetty12-version>

    <!-- Other dependencies -->
    <jackson-version>2.19.2</jackson-version>
    <junit5-version>6.0.0</junit5-version>
    <servlet-api-version>5.0.0</servlet-api-version>
    <slf4j-version>2.0.11</slf4j-version>

    <!-- Used for maven-frontend-plugin -->
    <node-version>v22.15.1</node-version>
    <yarn-version>v1.22.22</yarn-version>

    <!-- Maven plugins -->
    <build-helper-maven-plugin-version>3.6.1</build-helper-maven-plugin-version>
    <docker-plugin-version>0.48.1</docker-plugin-version>
    <exec-maven-plugin-version>3.6.3</exec-maven-plugin-version>
    <frontend-maven-plugin-version>2.0.0</frontend-maven-plugin-version>
    <maven-antrun-plugin-version>3.2.0</maven-antrun-plugin-version>
    <maven-clean-plugin-version>3.5.0</maven-clean-plugin-version>
    <maven-compiler-plugin-version>3.15.0</maven-compiler-plugin-version>
    <maven-dependency-plugin-version>3.10.0</maven-dependency-plugin-version>
    <maven-failsafe-plugin-version>3.5.5</maven-failsafe-plugin-version>
    <maven-release-plugin-version>3.3.1</maven-release-plugin-version>
    <maven-resources-plugin-version>2.6</maven-resources-plugin-version>
    <maven-surefire-plugin-version>3.5.5</maven-surefire-plugin-version>
    <maven-war-plugin-version>3.5.1</maven-war-plugin-version>
  </properties>

  <modules>
    <module>quarkus</module>
    <module>quarkus-keycloak</module>
    <module>sample-plugin</module>
    <module>springboot</module>
    <module>springboot-authentication</module>
    <module>springboot-keycloak</module>
    <module>springboot-log4j2</module>
    <module>springboot-plugin</module>
    <module>springboot-security</module>
    <module>war-plugin</module>
  </modules>

  <build>
    <defaultGoal>install</defaultGoal>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>17</source>
          <testSource>17</testSource>
          <target>17</target>
          <testTarget>17</testTarget>
          <release>17</release>
          <testRelease>17</testRelease>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-integration-test-sources</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>src/integration-test/java</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-integration-test-resources</id>
            <phase>generate-test-resources</phase>
            <goals>
              <goal>add-test-resource</goal>
            </goals>
            <configuration>
              <resources>
                <resource>
                  <filtering>true</filtering>
                  <directory>src/integration-test/resources</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
        <configuration>
          <autoVersionSubmodules>true</autoVersionSubmodules>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <redirectTestOutputToFile>true</redirectTestOutputToFile>
          <forkedProcessTimeoutInSeconds>300</forkedProcessTimeoutInSeconds>
          <childDelegation>false</childDelegation>
          <useFile>true</useFile>
          <failIfNoTests>false</failIfNoTests>
          <failIfNoSpecifiedTests>false</failIfNoSpecifiedTests>
          <runOrder>alphabetical</runOrder>
          <systemPropertyVariables>
            <basedir>${basedir}</basedir>
            <java.awt.headless>true</java.awt.headless>
          </systemPropertyVariables>

          <excludes>
            <exclude>**/*IT.*</exclude>
            <exclude>**/*ITCase.*</exclude>
          </excludes>

          <includes>
            <include>**/*Test.*</include>
          </includes>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <executions>
          <execution>
            <id>integration-tests</id>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <excludes>
            <exclude>**/*Test.*</exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>

    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>${maven-clean-plugin-version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin-version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven-dependency-plugin-version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>${maven-failsafe-plugin-version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-release-plugin</artifactId>
          <version>${maven-release-plugin-version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven-surefire-plugin-version}</version>
        </plugin>
        <plugin>
          <artifactId>maven-war-plugin</artifactId>
          <version>${maven-war-plugin-version}</version>
        </plugin>
        <plugin>
          <groupId>com.github.eirslett</groupId>
          <artifactId>frontend-maven-plugin</artifactId>
          <version>${frontend-maven-plugin-version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>${build-helper-maven-plugin-version}</version>
        </plugin>
        <plugin>
          <groupId>io.fabric8</groupId>
          <artifactId>docker-maven-plugin</artifactId>
          <version>${docker-plugin-version}</version>
        </plugin>
        <plugin>
          <groupId>org.eclipse.jetty.ee10</groupId>
          <artifactId>jetty-ee10-maven-plugin</artifactId>
          <version>${jetty12-version}</version>
        </plugin>
      </plugins>
    </pluginManagement>

  </build>

  <profiles>
    <profile>
      <id>fastinstall</id>
      <properties>
        <skipTests>true</skipTests>
        <skip.yarn>true</skip.yarn>
      </properties>
    </profile>
  </profiles>

  <repositories>
    <repository>
      <id>redhat-ga-repository</id>
      <name>Red Hat GA Repository</name>
      <url>https://maven.repository.redhat.com/ga/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>redhat-ea</id>
      <name>Red Hat EA Repository</name>
      <url>https://maven.repository.redhat.com/earlyaccess/all</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <!-- Only when testing a staged release of new Jolokia version
    <repository>
      <id>orgjolokia-1074</id>
      <url>https://oss.sonatype.org/content/repositories/orgjolokia-1074/</url>
    </repository>
    -->
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>redhat-ga-repository</id>
      <name>Red Hat GA Repository</name>
      <url>https://maven.repository.redhat.com/ga/</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
    <pluginRepository>
      <id>redhat-ea</id>
      <name>Red Hat EA Repository</name>
      <url>https://maven.repository.redhat.com/earlyaccess/all</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>

</project>
